version: '3.5'
services:
  frontend:
    image: naitik1/proj-frontend # dockerhub repo link
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: naitik1/proj-backend # dockerhub repo link
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"