version: '3'
services:
  project-web-db:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    networks:
      - node-network
    ports:
      - 27017:27017
  project-frontend:
    image: naitik1/proj-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://proj-backend:3000/
    restart: always
    ports:
      - 3000:3000
  project-web-backend:
    image: naitik1/proj-backend:latest
    environment:
      MONGO_URL: mongodb+srv://vaibhavthapliyal19:naitik@cluster0.5bkzwu6.mongodb.net/?retryWrites=true&w=majority
    restart: always
    depends_on:
      - project-web-db
    volumes:
      - .:/src
    networks:
      - node-network
    ports:
      - 4000:4000
volumes:
  mongodata:
networks:
  node-network:
    driver: bridge